// 英语 - 四级
define(function () {
    return {
        content: `access\tv. 获取 n. 接近，入口
project\tn. 工程；课题、作业
intention\tn. 打算，意图
equivalence\tn. 等值，相等
negotiate\tv. 谈判，协商，交涉
disappointing\tadj. 令人失望的
alternative\tn. 代替品
generous\tadj. 慷慨的
biological\tadj. 生物的
strategy\tn. 策略，战略
paradox\tn. 悖论；自相矛盾
primary\tadj. 主要的，基本的
standpoint\tn. 立场
grab\tv. 抢先，抢占，抢夺
crucial\tadj. 至关重要的
flaw\tn. 缺点；错误
depressed\tadj. 萧条的；沮丧的
obstacle\tn. 阻碍
automatic\tadj. 自动的
passionate\tadj. 热情的
gambling\tn. 赌博
logic\tn. 逻辑
theory\tn. 理论
download\tv. 下载
signal\tn. 信号 v. 发信号，打信号；示意
authoritative\tadj. 权威的
smooth\tadj. 光滑的
institution\tn. 社会公共机构；制度；设立，制定
vehicle\tn. 车辆
plague\tv. 使困扰
psychological\tadj. 心理上的
shade\tn. 阴凉处
persistent\tadj. 持续的；坚持的
voluntary\tadj. 自愿的，主动的
tolerance\tn. 宽容，容忍
senior\tn. 老年人
individual\tn. 个人
contemporary\tadj. 当代的，现代的
opposite\tadj. 相反的
specialize\tv. 专业从事
content\tn. 内容
philosopher\tn. 哲学家
unrest\tn. 不安定，动荡
startle\tv. 吃惊
emission\tn. 排放，辐射
overweight\tadj. 超重的
occupation\tn. 职业，工作
mainstream\tn. 主流
scholarship\tn. 奖学金
contract\tn. 合同
cheek\tn. 脸颊
interdependence\tn. 相互依靠
import\tn. 进口 v. 进口
fiction\tn. 小说，虚构的文学作品
upbringing\tn. 养育，培养，教养
preserve\tv. 保护
vitally\tadv. 极其重要地
masculine\tadj. 男性的
advocate\tv. 倡导 n. 提倡者，拥护者，鼓吹者
dust\tn. 灰尘
track\tn. 足迹 v. 追踪，〔循着踪迹、气味等〕找寻
confidence\tn. 信心
riotous\tadj. 狂暴的
sophisticated\tadj. 复杂的；世故的
similar\tadj. 相似的
transform\tv. 改变
approve\tv. 赞成，同意
session\tn. 开会，会议
awareness\tn. 意识
exhaust\tv. 使筋疲力尽
subsidize\tv. 提供补贴
grocery\tn. 杂货店
ignorance\tn. 无知，愚昧
intelligence\tn. 智力，智慧，理解力
tiny\tadj. 微小的
praise\tv. 赞扬，赞美
memorize\tv. 熟记，牢记
relative\tadj. 相对的 n. 亲戚
breakthrough\tn. 突破
incidence\tn. 几率，发生率
scratch\tn. 抓，划痕
harmful\tadj. 有害的
undergo\tv. 承受
recession\tn. 衰退
extraordinary\tadj. 非凡的
improper\tadj. 不合适的，不适当的
marginalize\tv. 边缘化，排斥
vital\tadj. 重要的
fortunately\tadv. 幸运地
commencement\tn. 毕业典礼
fetch\tv. 取回
clumsy\tadj. 笨拙的，不圆滑的
establishment\tn. 确立
emit\tv. 发出，排出
entertaining\tadj. 有趣的，使人愉快的
irregular\tadj. 不规律的
psychologist\tn. 心理学家
era\tn. 纪元，年代
triumph\tn. 胜利
detection\tn. 侦查；察觉
cozy\tadj. 舒适的
gallery\tn. 美术馆
enormous\tadj. 巨大的
obtain\tv. 获得
desert\tv. 抛弃
aviate\tv. 驾驶飞机
determine\tv. 决定；下决心
disappear\tv. 不见，消失
entitle\tv. 使具有权利，使具有资格
relieve\tv. 解除，减轻，缓解
generosity\tn. 慷慨，大方
colleague\tn. 同事
undertake\tv. 承担
convenient\tadj. 方便的
preferentially\tadv. 优先地
column\tn. 专栏
affectionate\tadj. 深情的，柔情的
issue\tv. 发表〔声明〕 n. 问题
inquire\tv. 询问
groundlessly\tadv. 无缘无故地，无根据地
independently\tadv. 独立地
approach\tv. 靠近 n. 方法
administration\tn. 管理；〔某一时期的〕政府
adversity\tn. 逆境，不幸
technician\tn. 技术员，技师
regular\tadj. 有规律的，经常的
miscalculation\tn. 算错，误算
hinder\tv. 阻碍
selection\tn. 选择，挑选
tide\tn. 潮水
superior\tadj. 上级的，较高的 n. 上级，长官
matter\tv. 要紧，重要
passively\tadv. 消极地
grant\tv. 授予；允许
liberation\tn. 解放
observe\tv. 遵守
institute\tv. 建立 n. 〔从事科研或教育等的〕机构；学院；研究院
dormitory\tn. 宿舍
awful\tadj. 可怕的，骇人的
emergency\tn. 紧急情况
stress\tn. 压力；重音
launch\tv. 发动
suppose\tv. 料想，以为；假定；期望
remove\tv. 消除，移除
exposure\tn. 暴露；揭露
promote\tv. 促进，提升；推销
engage\tv. 从事；吸引
uncertain\tadj. 不确定的
accommodate\tv. 为…提供住宿
slave\tn. 奴隶
mature\tadj. 成熟的
contrast\tn. 对照物 v. 对比
clinic\tn. 诊所
award\tv. 授予；判给 n. 奖(金)
worthwhile\tadj. 有价值的
cruelty\tn. 残暴，残酷
threaten\tv. 威胁
chemical\tadj. 化学的 n. 化学制品
consistent\tadj. 一致的
renew\tv. 〔中止后〕重新开始，继续
takeoff\tn. 起飞
innocent\tadj. 无辜的；天真的
currently\tadv. 当前；一般地
dropout\tn. 辍学者
replace\tv. 代替
sightseeing\tn. 观光
honor\tn. 荣誉；崇敬，敬重，敬意
imitate\tv. 模仿
installment\tn. 分期付款
personality\tn. 个性，性格
headquarter\tv. 设立总部，在…设立总部
ingredient\tn. 成分，原料
revenue\tn. 收入
sensitive\tadj. 敏感的
particular\tadj. 特别的，特指的；讲究的；挑剔的，吹毛求疵的
tumor\tn. 瘤
consequence\tn. 结果，成果
explicitly\tadv. 直接地，明确地
sway\tv. 影响
technical\tadj. 技术的
expert\tadj. 熟练的，内行的
harm\tn. 损害；危害；伤害 v. 伤害，损害〔某事物〕
imaginary\tadj. 虚构的，想象的
contaminate\tv. 污染，弄脏
soar\tv. 猛增
solely\tadv. 单独地，唯一地
tremendous\tadj. 巨大的
civilization\tn. 文明
tough\tadj. 困难的
gift\tn. 礼物；天赋
scale\tn. 规模；比例
injure\tv. 使受伤
embrace\tv. 拥抱；欣然接受，乐意采纳 (新思想、意见、宗教等)
seldom\tadv. 很少，罕见
performance\tn. 演出；履行；表现
violate\tv. 违反
associate\tv. 把……联系起来；交往；
privacy\tn. 隐私
choke\tv. 使窒息
capable\tadj. 能干的，有能力的
appeal\tn. 呼吁 v. 吸引；呼吁；恳请，恳求
careless\tadj. 粗心的
hit\tn. (唱片、电影或戏剧的) 成功；命中，击中
swallow\tv. 咽下，吞下
consult\tv. 咨询
preservation\tn. 保存，保留
distance\tn. 距离
plastic\tadj. 塑料的
predict\tv. 预言，预测，预告
submit\tv. 提交
entertainment\tn. 娱乐
critical\tadj. 批评的，爱挑剔的
transaction\tn. 交易，业务，事务
via\tprep. 通过
insist\tv. 主张，坚持
distract\tv. 分心
subdivision\tn. 分支; 分部
yield\tv. 产生，得出〔结果、答案或资料 n. 产量
misunderstand\tv. 误解
detail\tn. 细节
immeasurable\tadj. 无法估量的
convincing\tadj. 令人信服的
donate\tv. 捐赠
compare\tv. 比较，对照
item\tn. 〔尤指清单上、一群或一组事物中的〕一项，一件，一条
concrete\tadj. 具体的
govern\tv. 管理，支配
classify\tv. 把…分类，把…分级
restrict\tv. 限制，限定
establish\tv. 建立，创办，设立
counseling\tn. 咨询服务
majority\tn. 多数
contact\tn. 联系，接触 v. 〔写信、打电话〕联系〔某人〕
virtual\tadj. 虚拟的
simplicity\tn. 简单
enrollment\tn. 入学人数
programming\tn. 〔计算机的〕程序编写，程序设计；程序；；〔电视或广播〕节目；电视[广播]节目策划，编排
device\tn. 装置，设备
previous\tadj. 之前的
alter\tv. 改变
coach\tn. 教练 v. 当…的教练，训练，培训
crisis\tn. 危机
interconnect\tv. 相互联系
enrich\tv. 丰富；使富有
poll\tn. 民意调查
consent\tv. 允许，同意 n. 同意，赞同
utility\tn. 公用事业〔如煤气、电力等〕
poisonous\tadj. 有毒的，有害的
collision\tn. 冲突，抵触
rank\tv. 具有…等级[地位] n. 衔，阶层
fundamentally\tadv. 根本上
inflation\tn. 通货膨胀
secure\tv. 确保……安全
interpret\tv. 解释
criticize\tv. 批评；评论
arrest\tv. 逮捕
afford\tv. 负担得起
implementation\tn. 实现，履行
initiate\tv. 开始，发起
enable\tv. 使能够……
narrow\tadj. 狭窄的
overcharge\tv. 向……多收费
shortcut\tn. 捷径，近路
leisure\tn. 悠闲，空闲
original\tadj. 原始的，最初的
density\tn. 密度
sphere\tn. 球体；范围
margin\tn. 页边的空白，页边，白边
department\tn. 部门
desire\tn. 渴望，欲望
legend\tn. 传奇
dictator\tn. 独裁者；专制者
diversity\tn. 多样性；差异
quit\tv. 放弃
outgoing\tadj. 开朗的；外向的；外出的
solution\tn. 解决，解答，解决办法
revenge\tn. 报仇
reverse\tn. 相反情况；正相反 a. 相反的
enroll\tv. 注册
logically\tadv. 合乎情理地，符合逻辑地
rental\tn. 租金
component\tn. 成分
quotation\tn. 引文
faith\tn. 信任
invalid\tadj. 无效的
invade\tv. 侵入，侵略
separately\tadv. 分别地，另行
strain\tv. 扭伤，拉伤
accessible\tadj. 易接近的
lap\tn. 〔坐着时的〕大腿部
character\tn. 角色
widespread\tadj. 普遍的，广泛的
rearrange\tv. 重新安排
hospitalize\tv. 就医
avail\tv. 有益, 有帮助
instant\tadj. 立即的；紧急的；速溶的，方便的
democratic\tadj. 民主的
barely\tadv. 仅仅，几乎不
vanish\tv. 消失
caregiver\tn. 照料者
harsh\tadj. 严酷的
reliable\tadj. 可靠的，可信赖的
massive\tadj. (尺寸、数量、规模) 非常大的
alcohol\tn. 酒精
pregnant\tadj. 怀孕的
adapt\tv. 适应于
bogus\tadj. 假冒的
slippery\tadj. 滑的；模糊的，不明确的，
current\tadj. 当前的
overwhelm\tv. 压倒，战胜
stressful\tadj. 充满著压力的，充满著紧张的
toothache\tn. 牙痛，牙疼
eliminate\tv. 消除
terminal\tn. 终点站，航空站
severe\tadj. 严重的
immobile\tadj. 稳定的，不变的
diplomatic\tadj. 外交的
candidate\tn. 申请求职者；投考者；候选人
fund\tn. 基金，储备； v. 提供资金
complacency\tn. 自满，满足
delight\tn. 高兴
inadequate\tadj. 不足的，不够的
steady\tadj. 稳定的，逐步的
accurate\tadj. 精确的，准确的
identification\tn. 身份证明；鉴定，识别；认同；
previously\tadv. 事先
identical\tadj. 相同的
retirement\tn. 退休
commit\tv. 犯罪；承担义务
element\tn. 要素；元素
assess\tv. 评价
hire\tv. 雇佣
represent\tv. 代表
overestimate\tv. 对（数量）估计过高
supervision\tn. 监督
expose\tv. 暴露
seemingly\tadv. 表面上看
assignment\tn. 作业
preference\tn. 偏爱
energetic\tadj. 精力充沛的
application\tn. 申请；应用
moral\tadj. 精神上的, 道德的
dispute\tn. 辩论，争论 v. 辩论，争论
influence\tn. 影响 v. 影响
illegal\tadj. 非法的
esteem\tn. 自尊
abundant\tadj. 大量的，丰富的
survey\tv. 调查；审视，仔细考虑 n. 调查；勘测，测量，测绘
extensively\tadv. 广泛地
deserve\tv. 值得
crash\tv. 坠落;坠毁;撞击 n. 〔汽车的〕撞车事故；〔飞机的〕坠毁，失事
affirm\tv. 断言，声明
reputation\tn. 名气，名声，名誉
degree\tn. 程度
fade\tv. 逐渐消失
competitor\tn. 竞争者，对手
confuse\tv. 使混淆，迷惑
task\tn. 任务，工作
lessen\tv. 减少
admit\tv. 承认；容许
bow\tv. 鞠躬
division\tn. 除法；部门
literature\tn. 文学，文学作品；文献；文献
consultant\tn. 顾问
penalty\tn. 惩罚
comment\tn. 评论
major\tadj. 主要的 v. 主修
option\tn. 选择
socialize\tv. 交往，联谊
bureau\tn. 局
budget\tn. 预算 v. 编预算
pop\tv. 突然出现，跳出
position\tn. 职位
unaffordable\tadj. 买不起的，负担不起的
function\tn. 功能 v. 运行
perceive\tv. 察觉
reserve\tv. 留出，预定
innovation\tn. 改革，创新
alert\tv. 提醒；使〔某人〕意识到 adj. 机警的
cautious\tadj. 谨慎的
document\tn. 文件
characterize\tv. 以……特点
achieve\tv. 完成，实现
address\tv. 解决
inspiration\tn. 灵感
agency\tn. 机构
formulate\tv. 规定，制定
fate\tn. 命运
surf\tv. 冲浪
steer\tv. 驾驶
structure\tn. 结构
architect\tn. 建筑师
frame\tn. 框架
amaze\tv. 使吃惊
affirmation\tn. 断言，肯定
intelligent\tadj. 有智慧的，聪明的，悟性强的
code\tn. 代码，密码
burden\tn. 重担，负担
absorb\tv. 吸收（液体、气体等）
instruction\tn. 用法说明；操作指南；命令，指示
admission\tn. 承认；准许进(加)入；入场费
additional\tadj. 额外的
prejudice\tn. 偏见 v. 使有偏见，使有成见
process\tn. 过程，进程；；工序；工艺流程 v. 处理
elegant\tadj. 优雅的
hospitable\tadj. 热情友好的
refreshing\tadj. 恢复活力的
ensure\tv. 确保
frighten\tv. 使惊恐，使恐慌
civilized\tadj. 文明的
approval\tn. 批准，认可；赞成，同意
publicize\tv. 宣布
resident\tn. 居民
considerate\tadj. 体贴的；考虑周到的
twist\tv. 扭曲，使弯曲
citizen\tn. 市民，城镇居民；公民
stake\tn. 风险
keenly\tadv. 敏锐地
superficial\tadj. 肤浅的
flexibility\tn. 灵活性；适应性
favorable\tadj. 赞同的
competent\tadj. 胜任的，有能力的
emotional\tadj. 情绪(上)的，情感(上)的；激起感情的； 敏感的；情绪激动的〔尤指哭泣〕
pioneer\tv. 开拓，开发
sustain\tn. 维持
gloomy\tadj. 阴沉的，沮丧的
convince\tv. 使相信
profitable\tadj. 有利可图的，有益的
routinely\tadv. 例行公事地
phenomenon\tn. 现象
variety\tn. 多样
gum\tn. 牙龈
criticism\tn. 批评
fatal\tadj. 致命的，攸关的
delightful\tadj. 高兴的
tedious\tadj. 单调沉闷的
flexible\tadj. 灵活的
considerably\tadv. 相当地，非常地
efficiently\tadj. 有效地
appearance\tn. 外表, 外观；出现
album\tn. 粘贴簿，集邮簿，册
optimistic\tadj. 乐观的
clue\tn. 线索
grief\tn. 悲伤
synthetic\tadj. 合成的，人造的
resistance\tn. 抵御，抵抗；抵抗力
install\tv. 安装
pledge\tn. 保证，誓言
unique\tadj. 独特的，唯一的
stock\tn. 股票；库存
disadvantage\tn. 不利情况，缺点
compensate\tv. 弥补，补偿
rescue\tv. 营救，援救
monitor\tv. 监控；监听
refusal\tn. 拒绝
exile\tn. 流放，放逐
encourage\tv. 鼓励
concept\tn. 观点，观念
render\tv. 给予
trait\tn. 性格
feature\tn. 特点
reframe\tv. 再构造(图画、照片等)
identify\tv. 认出，识别；视为
impose\tv. 强加
snack\tn. 零食，小吃
require\tv. 要求，命令
donation\tn. 捐赠
equal\tadj. 相等的，平等的
rare\tadj. 罕有的，少见的
specify\tv. 指定，具体说明
constant\tadj. 不断的，持续的
standardize\tv. 使标准化
consume\tv. 消费，消耗
status\tn. 地位
complement\tv. 补充
lengthy\tadj. 长的，漫长的
embarrassed\tadj. 尴尬的；窘迫的
rational\tadj. 神智清楚的
distant\tadj. 遥远的
homemaker\tn. 主妇
exception\tn. 例外
sustainable\tadj. 可持续的
trigger\tv. 引发，引起
intend\tv. 打算
spread\tv. 扩散；传播
estimate\tv. 估计
technique\tn. 技巧，手艺；技术，技能
include\tv. 包含
academic\tadj. 学术的
distinctive\tadj. 独特的，与众不同的
consist\tv. 由……组成
bid\tn. 出价，投标 v. 出价，投标
benefit\tv. 有益于，有助于
downsize\tv. 裁员
avoid\tv. 避免
gender\tn. 性别
interracial\tadj. 种族间的
complaint\tn. 抱怨; 投诉
pattern\tn. 模式
mood\tn. 心情
sympathy\tn. 同情心
discount\tn. 折扣
value\tv. 重视
altitude\tn. 海拔, 高度
groundsheet\tn. 防潮布
evolutionary\tadj. 进化的；演变的
implement\tv. 实施，执行
dominant\tadj. 占优势的
scope\tn. 范围
suspect\tv. 怀疑，猜想 n. 嫌疑犯
confrontation\tn. 冲突，对抗
puzzle\tv. 迷惑 n. 难解之事，谜
critic\tn. 批评家，评论家
apartment\tn. 公寓
analyze\tv. 分析
maintain\tv. 维持；主张
curb\tv. 控制 n. 控制
version\tn. 版本
rival\tn. 对手
beneficial\tadj. 有利的，有益的
substantial\tadj. 大量的
recover\tv. 恢复；重新获得；寻回
diploma\tn. 文凭
carpenter\tn. 木匠
circumstance\tn. 环境，境遇
canteen\tn. 食堂
advocator\tn. 主张者，倡导者
disorderly\tadj. 杂乱的
essentially\tadv. 本质上，根本上
prevent\tv. 预防
ceremony\tn. 典礼，仪式
assume\tv. 假定，认为
demand\tn. 需求，要求 v. 要求
principle\tn. 原则，原理
reception\tn. 接待；反响
transfer\tv. 转换，调换 n. 转换，调换
preventable\tadj. 可预防的
anticipate\tv. 预感
assumption\tn. 假定，假设
prescription\tn. 处方
evolution\tn. 演变，进化
annoy\tv. 使反感，厌烦
unintended\tadj. 意想不到的
origin\tn. 起源
qualify\tv. 使……有资格
emergence\tn. 出现，发生
complain\tv. 抱怨
merit\tn. 优点，成绩 v. 值得
forum\tn. 论坛
arrange\tv. 安排，筹划
determination\tn. 意志
bargain\tn. 便宜货，减价品
appetite\tn. 欲望, 胃口
neutral\tadj. 中立的
primitive\tadj. 原始的；简单的；简单的，简陋的
therapy\tn. 疗法 治疗
conscience\tn. 良心
define\tv. 确定；下定义
creativity\tn. 创造力
tailor\tv. 调整使适应
dramatically\tadv. 戏剧性地，引人注目地
panic\tn. 惊恐
motivation\tn. 激励，刺激
durable\tadj. 持久的，耐用的
remedy\tn. 药物
inevitable\tadj. 不可避免的
diverse\tadj. 各种各样的
context\tn. 背景，环境
prominent\tadj. 杰出的；突出的，凸起的
witness\tn. 目击者，目击
save\tv. 节省
inherit\tv. 继承
occasion\tn. 场合
initiative\tn. 主动权，自主权
insight\tn. 洞察力，洞悉
misguided\tadj. 被误导的
sponsor\tv. 赞助
porter\tn. 搬运工
loyalty\tn. 忠诚，忠实
overwhelming\tadj. 压倒性的
appreciation\tn. 感激
setting\tn. 背景，环境
display\tn. 展览 v. 展览
deliver\tv. 发表
astonish\tv. 使惊讶，使大为吃惊
adequate\tadj. 足够的
consumption\tn. 消费，消耗
abuse\tv. 虐待；滥用
broad\tadj. 宽的
inappropriate\tadj. 不合适的
worldwide\tadv. 全世界范围地
strict\tadj. 严格的
means\tn. 方法
reveal\tv. 揭露，揭示
confirm\tv. 证实
consensus\tn. 一致意见
agent\tn. 代理商
neighborhood\tn. 地区
participate\tv. 参与，参加
valid\tadj. 有效的
initially\tadv. 最初，起初
slightly\tadv. 轻微地
objection\tn. 反对
atmosphere\tn. 气氛；大气；空气
assign\tv. 布置；分配
evidence\tn. 根据，证据，迹象
racially\tadv. 种族上地
exclude\tv. 排除，不包括
available\tadj. 可利用的，现有的；可获得的
puzzling\tadj. 令人困惑的
evaluation\tn. 评价，评估
irritate\tv. 激怒
distinguished\tadj. 显著的，杰出的
depressing\tadj. 令人沮丧的
mutually\tadv. 互相地
mission\tn. 使命，任务；代表团
migration\tn. 迁移，移民
site\tn. 场所，地址
expectation\tn. 期望
update\tv. 更新；使现代化
gear\tn. 齿轮 v. 使合适
reproductive\tadj. 生殖的，再生的
incredible\tadj. 不可思议的
backward\tadv. 向后
raise\tv. 提高；筹款；抚养
prohibit\tv. 禁止，阻止，防止
bother\tv. 麻烦；打扰
pose\tv. 摆姿势，装腔作势 n. 姿势
instrument\tn. 仪器，器械，工具
mask\tv. 掩饰
essential\tadj. 必须的；本质的
harvest\tn. 丰收，收获
reject\tv. 拒绝，驳回
advancement\tn. 进步，提升
skyrocket\tv. 突升，猛涨
characteristic\tn. 特点
implication\tn. 含义，暗示
measure\tn. 分量 v. 测量
replacement\tn. 代替
easygoing\tadj. 脾气随和的，温和的
squeeze\tv. 压，榨
exhibition\tn. 展览
responsibility\tn. 责任
enhance\tv. 提高；加强；增加
retain\tv. 保留,留用
convey\tv. 传达，传递
regulation\tn. 管理；规则
integrity\tn. 完整
combine\tv. 联合，结合
impermanency\tn. 非永久性
catalogue\tv. 把……编入目录
council\tn. 议会
prepare\tv. 做准备
inquiry\tn. 询问
tension\tn. 紧张
prompt\tadj. 迅速的；立刻的；及时的 v. 促使；激励
attendance\tn. 出席人数
retail\tn. 零售 v. 零售
image\tn. 形象，声誉，；印象
quantity\tn. 量，数量
inspector\tn. 检查员
endurance\tn. 耐力
simplify\tv. 简化
range\tn. 范围 v. 在范围内变化
accomplish\tv. 完成
treatment\tn. 治疗；对待
spare\tadj. 空闲的
welfare\tn. 幸福；福利
boost\tn. 推动 v. 促使，促进
consciousness\tn. 意识
patiently\tadv. 耐心地
decent\tadj. 正派的，体面的
review\tn. 回顾 v. 复习
considerable\tadj. 相当大(或多)的
misguide\tv. 误导
foundation\tn. 地基；基础；；基金会
postgraduate\tn. 研究生
prevail\tv. 流行，盛行
solid\tadj. 扎实的，坚实的
counsel\tv. 忠告，建议
maximum\tn. 最大值，最大量 a. 最大值的，最大量的
abstract\tadj. 抽象的
realistic\tadj. 现实的，实际的
ban\tv. 禁止
ashamed\tadj. 羞耻的；内疚的；惭愧的
solve\tv. 解决
reinforce\tv. 加强，强化
applicant\tn. 申请人
tuition\tn. 学费
persistence\tn. 坚持不懈
overcome\tv. 战胜，克服
bride\tn. 新娘
engagement\tn. 婚约
household\tn. 家庭，一家人
evaluate\tv. 评价
saint\tn. 圣人
delay\tv. 推迟，延期
private\tadj. 私人的
definition\tn. 定义
influential\tadj. 有影响力的
recommend\tv. 推荐；劝告；使受欢迎
frontier\tn. 边境
concern\tn. 重要的事情 v. 与…有关，关于
organ\tn. 器官
cite\tv. 引用
mechanism\tn. 机制，机能
contest\tn. 比赛
symptom\tn. 症状
deadline\tn. 最后期限
domination\tn. 主导
figure\tn. 人物；数字
imply\tv. 暗示；意味；
curiosity\tn. 好奇心
induce\tv. 引诱
acknowledge\tv. 承认(…的权威)
gym\tn. 体育馆，健身房
chef\tn. 厨师
sensible\tadj. 明智的
outline\tn. 梗概，提纲，草稿，要点
react\tv. 对……作出反应
committee\tn. 委员会
civilian\tn. 平民，百姓
domestic\tadj. 国内的
complex\tadj. 复杂的
locate\tv. 位于，定位
tighten\tv. 使变紧
physics\tn. 物理，物理学
foothold\tn. 立足处（攀登时脚踩的地方）
discharge\tv. 释放；排出；批准离开; 命令离开
advanced\tadj. 高级的
complicated\tadj. 复杂的，难懂的
needy\tadj. 贫穷的
stale\tadj. 乏味的，没有新意的
casual\tadj. 漫不经心的，随便的；偶然的
conform\tv. 相一致，遵守
recharge\tv. 再充电
annually\tadv. 每年，一年一次
frown\tv. 皱眉
decline\tv. 下降，减少；拒绝
originate\tv. 开始
prospect\tn. 前景；前途
curious\tadj. 好奇的
incentive\tn. 动机，刺激
virus\tn. 病毒
cultivate\tv. 培养， 养成
potential\tn. 潜力 adj. 有可能的；潜在的
reluctant\tadj. 不愿意的，勉强的
miserable\tadj. 痛苦的
persuasion\tn. 劝说
competitiveness\tn. 竞争力
restriction\tn. 限制，限定
minor\tadj. 小的
grain\tn. 谷物，粮食
rate\tn. 比率，速率
radically\tadv. 完全地，彻底地
distinct\tadj. 明显的；有区别的
equality\tn. 平等
hardworking\tadj. 苦干的，不辞辛劳的
qualification\tn. 资格(证明)，合格证书
bacteria\tn. 细菌
corporate\tadj. 团体的；法人的
undermine\tv. 逐渐削弱; 逐渐动摇
selfish\tadj. 自私的
cater\tv. 迎合
survival\tn. 幸存
favor\tv. 偏好, 较喜欢
conflict\tv. 冲突
client\tn. 客户
garage\tn. 车库
fatigue\tn. 疲劳，疲乏
plant\tn. 工厂
endanger\tv. 危及，危害，濒临危险
operation\tn. 手术；行动
handle\tv. 处理
laborious\tadj. 费力的
passion\tn. 热情，激情
cooperative\tadj. 合作的
inflate\tv. (使)膨胀
resourceful\tadj. 机智的
exaggerate\tv. 夸张
loan\tn. 贷款
vocabulary\tn. 词汇
illustrate\tv. 说明,阐明
overflow\tv. 溢出，淹没
fantasize\tv. 想象，幻想
amusing\tadj. 有趣的，好玩儿的
universal\tadj. 宇宙的，全世界的；普遍的
generate\tv. 产生
schedule\tn. 日程表
backslide\tv. 倒退，退步
particle\tn. 微粒
menu\tn. 菜单
reward\tn. 报答，奖赏 v. 报答，奖赏
reproduce\tv. 复制
worsen\tv. （使）变得更坏
feedback\tn. 反馈
equivalent\tadj. 相等的，相当的
resign\tv. 辞职
motivate\tv. 促动，激发，诱导
compel\tv. 强迫
revise\tv. 修订
dampen\tv. 抑制
prosperity\tn. 繁荣
flow\tn. 流动 v. 流动
humanity\tn. 人类〔总称〕；人性
sideways\tadv. 向侧面
pursue\tv. 追求
innovate\tv. 创新，革新
mill\tn. 工厂
promotional\tadj. 促销的
dump\tv. 扔下，倾倒；倾销
resist\tv. 抵抗，抗拒
source\tn. 来源
legal\tadj. 法律的
picky\tadj. 挑剔的
steal\tv. 偷窃
despite\tprep. 尽管
explosion\tn. 爆炸
gap\tn. 缝隙，缺口；差距
relevant\tadj. 有关的，切题的
ignore\tv. 忽视，不顾
complete\tv. 完成 adj. 完整的，彻底的
sufficient\tadj. 足够的
switch\tv. 转变，改变
request\tn. 要求
stereotype\tn. 老套，固定模式
couple\tn. 夫妻，情侣
honesty\tn. 诚实
transportation\tn. 运输
physical\tadj. 身体上的
screen\tv. 筛查
divine\tadj. 神圣的
guideline\tn. 指导原则
revolution\tn. 革命
interruption\tn. 打扰；中断
dishwasher\tn. 洗碗机
promising\tadj. 有希望的，有前途的
vary\tv. 不同；变化
permanent\tadj. 永久的
manufacture\tv. 制造，生产
fussy\tadj. 爱挑剔的；
dictate\tv. 命令，规定 n. 命令，规定
professional\tadj. 专业的
prosper\tv. 繁荣
exchange\tn. 交换，交流 v. 交换，交流
concentration\tn. 集中
gesture\tn. 手势，姿势
deliberate\tadj. 故意的
contribution\tn. 贡献；捐款
bless\tv. 保佑，祝福
detective\tn. 侦探
evident\tadj. 明显的
retreat\tv. 退避，后退；撤退
responsible\tadj. 负责的，有责任的
identity\tn. 身份
statistics\tn. 统计学；数据
appreciate\tv. 感激；欣赏
insult\tv. 侮辱
neglect\tv. 疏忽；忽视
primarily\tadv. 主要地，首先
long\tv. 渴望
incline\tv. 倾向于
asset\tn. 有价值的人(或物)资产
overtake\tv. 超车
extension\tn. 分机
engine\tn. 引擎，发动机
emphasize\tv. 强调
genuine\tadj. 真正的
fascination\tn. 魅力；入迷
lodge\tv. 住宿，暂住
cheat\tv. 欺骗, 作弊
security\tn. 安全，安保
painful\tadj. 痛苦的，疼痛的，令人不快的
emerge\tv. 出现
instance\tn. 情况，例子
steep\tadj. 陡峭的；急剧升/降的
rigorous\tadj. 严格的
persuade\tv. 说服
procedure\tn. 程序
signature\tn. 签名
surpass\tv. 超过
campaign\tn. 活动
advance\tn. 提前 v. 前进
charity\tn. 慈善机构
average\tadj. 平常的
indispensable\tadj. 必不可少的
irrationally\tadv. 不合理地，无理性地
accompany\tv. 陪伴
aviation\tn. 航空
distress\tv. 使痛苦，悲痛
invariably\tadv. 不变地，一直
invest\tv. 投资
approximately\tadv. 大约
conservation\tn. 保护，保存
ease\tn. 轻松，舒适
extracurricular\tadj. 课外的
undoubtedly\tadv. 无疑
excellent\tadj. 卓越的，杰出的，极好的
investigate\tv. 调查
judgement\tn. 判断，决定
struggle\tv. 搏斗
prohibitively\tadv. 过分地，非常地
military\tadj. 军队的，军事的
consequently\tadv. 结果
suffer\tv. 受苦；遭受（痛苦）
visible\tadj. 看得见的
swift\tadj. 迅速的
battle\tn. 战争，战役
liability\tn. 责任
resistant\tadj. 抵抗的；抵制的
nutritious\tadj. 营养的
constantly\tadv. 不断地，时常地
familiar\tadj. 熟悉的
terribly\tadv. 可怕地，非常
restore\tv. 修复
refine\tv. 改善；精炼
inspire\tv. 激发；鼓舞；使产生灵感
comply\tv. 遵从
justice\tn. 公正
district\tn. 区
installation\tn. 安装；就职；就职仪式
marvelous\tadj. 引起惊异的
provoke\tv. 激起，挑起
lobby\tn. 大堂 v. 游说
interview\tn. 面谈（试）；会见； v. 采访 ；面试
release\tv. 释放；发布
explore\tv. 探索
profound\tadj. 深厚的
exploit\tv. 开采
startup\tn. 启动，开办
constructive\tadj. 建设的，建设性的
unbearable\tadj. 无法忍受的
laundry\tn. 要洗的衣服；刚洗过的衣物；洗衣房
seize\tv. 抓住
poison\tv. 使中毒
bakery\tn. 面包店
tent\tn. 帐篷
wedding\tn. 婚礼
fair\tn. 集市
geographic\tadj. 地理的
comprehensive\tadj. 综合的，全面的
riot\tn. 暴乱
conspicuous\tadj. 显著地
block\tv. 阻碍 n. 街区
acute\tadj. 敏锐的
endure\tv. 忍耐；容忍
assembly\tn. 装配
opponent\tn. 对手
confront\tv. 面对
stir\tv. 搅动；煽动，激起
rocket\tn. 火箭 v. 猛增
attribute\tv. 归因于
sentence\tn. 判决 v. 判决
tempting\tadj. 诱人的，吸引人的
commitment\tn. 承诺，保证
feasible\tadj. 可行的；可能的；可用的
outcome\tn. 结果
diligent\tadj. 勤奋的
deprive\tv. 剥夺，夺去，使丧失
grid\tn. 输电网
distribute\tv. 分发
destruction\tn. 破坏
divide\tv. 分开
highlight\tv. 突出；强调 n. 突出的部分
justify\tv. 证明……正当
announce\tv. 宣布，声称
proposal\tn. 提议
advisory\tn. 报告，警告
mystery\tn. 迷，神秘的事物
punctual\tadj. 准时的
derive\tv. 得到，导出
harmony\tn. 和谐
unwilling\tadj. 不愿意的
view\tv. 看待
financial\tadj. 财政的，经济的
priority\tn. 优先，优先权
impermanent\tadj. 非永久（性）的；不持久的，暂时的
symbolize\tv. 象征
bankrupt\tadj. 破产的，倒闭的
intake\tn. 摄入
addiction\tn. 上瘾
productive\tadj. 富有成效的
admire\tv. 钦佩，称赞
reflect\tv. 反映
underline\tv. 强调
representative\tn. 代表
blame\tv. 指责，责怪
retrain\tv. 再教育；再训练
tasteless\tadj. 无味的
excessive\tadj. 过度的
dishonest\tadj. 不诚实的
caution\tn. 小心，谨慎 v. 警告，告诫
glorious\tadj. 辉煌的
pointless\tadj. 无意义的
significant\tadj. 重要的
mutual\tadj. 相互的
temptation\tn. 诱惑，引诱
passive\tadj. 被动的
evolve\tv. 使发展
treasure\tv. 珍爱
shock\tv. 感到震惊
disservice\tn. 伤害，帮倒忙
ambitious\tadj. 有雄心的，野心勃勃的
fancy\tadj. 华丽的；别致的
accumulate\tv. 积累，增加
fuss\tn. 大惊小怪
ultimately\tadv. 最后，最终
showmanship\tn. 主持演出的技巧
cancel\tv. 取消
regulate\tv. 管理
peer\tn. 同龄人
calculate\tv. 计算
virtually\tadv. 几乎，差不多
accustom\tv. 使习惯
retailer\tn. 零售商
programmer\tn. 程序设计员
advice\tn. 建议
admiration\tn. 钦佩，称赞
courageous\tadj. 有勇气的
respectful\tadj. 有礼貌的，尊重的
makeup\tn. 化妆品
reservation\tn. 预定
apply\tv. 申请；应用
demonstrate\tv. 证明；展示
generation\tn. 一代人；产生
chat\tv. 聊天
ancient\tadj. 古代的
evil\tn. 邪恶，罪恶
indifferent\tadj. 冷漠的
namely\tadv. 即，也就是
effect\tn. 影响
devote\tv. 奉献，致力于
appointment\tn. 约会
appoint\tv. 任命，委派；约定，确定，指定
resemble\tv. 像，相似
assemble\tv. 集合；组装；集合
expressiveness\tn. 表达
visibility\tn. 能见度
distracted\tadj. 分心的
debt\tn. 债务`

    }
})
